name: Build and publish 📦

inputs:
  test:
    required: false
    type: boolean
    default: false
  github-token:
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - name: Build
      uses: ./.github/actions/build
    - name: Publish
      uses: ./.github/actions/publish
      with:
        test: ${{ inputs.test }}
        github-token: ${{ inputs.github-token }}
