name: Build and publish 📦

on:
  workflow_call:
    inputs:
      test:
        required: false
        type: boolean
        default: false

jobs:
  build:
    name: Build distribution 📦
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6
      with:
        persist-credentials: false

    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: "3.x"

    - name: Install pypa/build
      run: python3 -m pip install --upgrade build
      # run: python3 -m pip install build --user

    - name: Build a binary wheel and a source tarball
      run: python3 -m build

    - name: Store the distribution packages
      uses: actions/upload-artifact@v5
      with:
        name: python-package-distributions
        path: dist/

  publish:
    name: Publish to ${{ inputs.test && 'Test PyPI' || 'PyPI' }}
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: ${{ inputs.test && 'test_pypi' || 'pypi' }}
      url: ${{ inputs.test && 'https://test.pypi.org/p/escansi' || 'https://pypi.org/p/escansi' }}
    permissions:
      id-token: write
      attestations: write
      artifact-metadata: write
    steps:
    - name: Download all the dists
      uses: actions/download-artifact@v6
      with:
        name: python-package-distributions
        path: dist/

    - name: Install Twine
      run: python3 -m pip install --upgrade twine

    - name: Attest the distribution packages
      uses: actions/attest@v4
      with:
        subject-path: dist/

    - name: Publish distribution 📦 to ${{ inputs.test && 'Test PyPI' || 'PyPI' }}
      run: python3 -m twine upload --repository ${{ inputs.test && 'testpypi' || 'pypi' }} dist/*
