name: Publish to PyPI

on: workflow_dispatch

concurrency:
  group: pypi_publish
  cancel-in-progress: true

jobs:
  publish:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/escansi
    permissions:
      id-token: write # Mandatory for trusted publishing
    steps:
    - name: Download all the dists
      uses: actions/download-artifact@v6
      with:
        name: python-package-distributions
        path: dist/
    - name: Publish distribution 📦 to PyPI
      uses: pypa/gh-action-pypi-publish@v1.14.0 # Already attestated