name: Publish to PyPI

on: workflow_dispatch

concurrency:
  group: test_pypi_publish
  cancel-in-progress: true

jobs:
  build_and_publish:
    name: Build and publish 📦
    uses: ./.github/workflows/publish.yml
    with:
      test: true
