name: Publish to PyPI

on: workflow_dispatch

concurrency:
  group: pypi_publish
  cancel-in-progress: true

jobs:
  build_and_publish:
    name: Build and publish 📦
    permissions:
      id-token: write
    uses: ./.github/workflows/build_and_publish.yml
    with:
      test: false
